### ISSUE TITLE
let_it_be, before_all and timecop bug?

### ISSUE THREAD

**Issue by SynthesisOne** [test-prof/test-prof#217]
Hello, I don't know if this is a bug, but if you use let_it_be together with Timecop, you get two results, if you use
before_all {Timecop.freeze (Time.zone.local (2020, 7, 30, 15))}
then the dates specified in the factory using let_it_be use Timecop correctly, but at the same time tests that are wrapped in several contexts do not use dates from Timecop, but if you run them separately, then everything works correctly, and if you use
standard before {Timecop.freeze (Time.zone.local (2020, 7, 30, 15))} then already the let_it_be factory does not see the date from Timecop but inside tests the time is taken from Timecop.

**Comment by SynthesisOne** [comment]
Addition: the test does not use the date from timecop (inside before_all) only if it is not run separately, but if it is run from a twice nested context or describe

**Comment by SynthesisOne** [comment]
temporary solution: use simultaneously

`  before { Timecop.freeze(Time.zone.local(2020, 7, 30, 15)) }
  before_all { Timecop.freeze(Time.zone.local(2020, 7, 30, 15)) }`

**Comment by palkan** [comment]
Looks like you call `Timecop.return` after every example (maybe, in the RSpec configuration). That's why a single test passes when setting time within `#before_all` but the next one fails.

So, repeating the same Timecop command in both `before_all` and `before` is a viable option.

Alternatively, you may use some variable to conditionally call `Timecop.return`. For example, we can use metadata for that:

```ruby
Rspec.configure do |config|
  config.after(:each) do |example|
    Timecop.return unless example.metadata[:timecop] == :no_return
  end
end

# in the spec
describe "Something", timecop: :no_return do
  before_all do
    Timecop.freeze(1.day.ago)
    # ...
  end

  # Make sure you return in the end
  after_all { Timecop.return }
end
```
