### ISSUE TITLE
Strange behavior with frozen objects

### ISSUE THREAD

**Issue by marcocarvalho** [test-prof/test-prof#224]
### Tell us about your environment

ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
Rails 6.1.4.1
RSpec 3.10
  - rspec-core 3.10.1
  - rspec-expectations 3.10.1
  - rspec-mocks 3.10.2
  - rspec-rails 5.0.2
  - rspec-support 3.10.2
 factory_bot (6.2.0)
    factory_bot_rails (6.2.0)
      factory_bot (~> 6.2.0)
  factory_bot_rails (~> 6.2.0)
 test-prof (1.0.6)

### What did you do?

I have a bunch of shared examples combined with shared contexts. We have a Parent->Child relation where the parent has a count of the child. In the real world, we do this count in async jobs, but in the tests, for the sake of simplicity, we do an `after(:create) { |child| child.parent.update_column(:count, child.parent.childs.count }`

But I get a strange behavior on frozen objects:

```ruby

# ======== models and factories =========

class Parent
  include ActiveModel::Model

  attr_accessor :count

  def initialize(*args)
    super
    self.count ||= 0
  end

  def reload
    self.class.new(count: count)
  end

  def save!
    self
  end
end

class Child
  include ActiveModel::Model

  attr_accessor :parent

  def reload
    self.class.new(parent: parent)
  end

  def save!
    self
  end
end

FactoryBot.define do
  factory :parent, class: Parent do
  end

  factory :child, class: Child do
    parent { Parent.new }

    after(:create) do |child|
      puts "child.parent.frozen? (#{child.parent.frozen?})"
      child.parent.count += 1
    end
  end
end

# ======= specs =======

shared_context "models A" do
  let_it_be(:child) { create(:child) }
  let_it_be(:parent, reload: true) { child.parent }
end

shared_context "models B" do
  let_it_be(:child2) { create(:child, parent: parent) }
end

RSpec.shared_examples "count models" do |number|
  it { expect(parent.count).to eq(number) }
end

RSpec.shared_examples "some shared example" do
  include_context "models A"

  context "some context" do
    it { is_expected.to eq("something")  }

    context "nested with extra context will fail if the model is referenced in the main describe" do
      include_context "models B"

      it_behaves_like "count models", 2
    end

    context "nested with extra context will not fail due to the workaround" do
      # workaround, it will work but will create all "models A" shared context once again.
      include_context "models A"
      include_context "models B"

      it_behaves_like "count models", 2
    end
  end
end

RSpec.describe "test-prof contexts", type: :model do
  it_behaves_like "some shared example" do
    # here the factory will receive a frozen object
    subject(:references_the_model) do
      parent.frozen? # can be anything, just call the model
      "something"
    end
  end

  it_behaves_like "some shared example" do
    # here, the factory does not receives a frozen object
    subject(:not_references_the_model) do
      "something"
    end
  end
end

```

### What did you expect to happen?

Even if I reference the model in the main describe, the factory should not receive a frozen object.

### What actually happened?

I receive a frozen object. Note: This example uses an ActiveModel::Model to simulate the error, and I implemented the reload. In my genuine spec, I'm using an active record model. I tried to use refind and reload options, but with no success.

![image](https://user-images.githubusercontent.com/503670/138683170-8239af43-5e5f-404c-86bf-2ed627b2d26b.png)

**Comment by palkan** [comment]
Thanks for the report and especially for the reproduction.
Will take a look soon.

**Comment by palkan** [comment]
I added a reproduction here: https://github.com/test-prof/test-prof/pull/228

First, commit adds a test based on your example. It passes.

Second one adds `freeze` modifier by default (via metadata); I guess, you have a similar setup, right? It shows the same error as you had.

The final commit adds `freeze: false` to `let_it_be(:parent)`: that's what we have to do here.

Why calling `parent.frozen?` breaks everything? Because modifiers are applied lazily, only when you use the definition in your code; under the hood we have something like `let(:parent) { let_it_be_records[:parent].reload.freeze }`. Since the second child is created in the nested context, the order of execution is as follows:
- `let_it_be(:child) { create(:child) }` # nothing is frozen here
- `let_it_be(:parent, reload: true) { child.parent }` # ditto
- `it { is_expected.to eq("something") }` # that's where subject is called; if we call parent inside — we freeze it
- `let_it_be(:child2) { create(:child, parent: parent) }` # we entered the nested context => Boom! Parent could be frozen here.
